### PR TITLE
[eas submit] Add missing iOS error messages

### LINKED ISSUE #115: [eas submit][ios] no app icon error message needs improvement
The output when an icon is missing is messy and could be improved.
```
tape-warm 𝝠 easd submit
✔ Choose a platform to submit to › iOS
✔ Ensuring @bacon/tape-warm is created on Expo

Ensuring your app exists on App Store Connect. This step can be skipped by providing the --asc-app-id
param. Learn more: https://expo.fyi/asc-app-id

Please enter your Apple Developer Program account credentials. These credentials are needed to manage
certificates, keys and provisioning profiles in your Apple Developer account.
The password is only used to authenticate with Apple and never stored on Expo servers
Learn more here https://docs.expo.io/distribution/security/#apple-developer-account-credentials
✔ Apple ID: … evanjbacon@gmail.com
Using password from your local Keychain. Learn more https://docs.expo.io/distribution/security#keychain
Restoring session /Users/evanbacon/.app-store/auth/evanjbacon@gmail.com/cookie
Logged in Local session restored

Ensuring that bundle ID "org.name.tapewarm" is registered on Apple Dev Center...
Checking App Store Connect for "tape-warm" (org.name.tapewarm)...
Creating app "tape-warm" (org.name.tapewarm) on App Store Connect...
App "tape-warm" (org.name.tapewarm) on App Store Connect is ready for your binary.
✔ What would you like to submit? › The latest build from Expo servers
┌─────────────────────────────────────────────────────────────────────────────────┐
│                             iOS Submission Summary                              │
├─────────────────────────┬───────────────────────────────────────────────────────┤
│ Archive URL             │ https://turtle-v2-artifacts.s3.amazonaws.com/ios/7    │
│                         │ 9a38488-7eb9-4ebc-9728-f02a842cc887-6eee499fda774f    │
│                         │ 98847316edbfcc541b.ipa                                │
├─────────────────────────┼───────────────────────────────────────────────────────┤
│ Apple ID                │ evanjbacon@gmail.com                                  │
├─────────────────────────┼───────────────────────────────────────────────────────┤
│ Apple app-specific      │ [hidden]                                              │
│ password                │                                                       │
├─────────────────────────┼───────────────────────────────────────────────────────┤
│  App Store Connect App  │ 1543439387                                            │
│ ID                      │                                                       │
├─────────────────────────┼───────────────────────────────────────────────────────┤
│ Project ID              │ cab65372-b7f1-4448-96af-00061fa92cae                  │
└─────────────────────────┴───────────────────────────────────────────────────────┘
✔ Scheduling submission
✖ Something went wrong when submitting your app to Apple App Store.
Please see logs

[logs] Starting iOS app upload
[logs] Downloading archive
[logs] Uploading iOS app to TestFlight...
[logs] [09:35:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[logs] [09:35:50]: -------------------
[logs] [09:35:50]: --- Step: pilot ---
[logs] [09:35:50]: -------------------
[logs] [09:35:50]: Ready to upload new build to TestFlight (App: 1543439387)...
[logs] [09:35:53]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[logs] [09:35:53]: Going to upload updated app to App Store Connect
[logs] [09:35:53]: This might take a few minutes. Please don't interrupt the script.
[logs] [09:37:12]: [Transporter Error Output]: ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"
[logs] [09:37:12]: [Transporter Error Output]: ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'org.name.tapewarm'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."
[logs] [09:37:12]: [Transporter Error Output]: ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[logs] [09:37:12]: Transporter transfer failed.
[logs] [09:37:12]: ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"
[logs] ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'org.name.tapewarm'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."
[logs] [09:37:12]: 
[logs] ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[logs] [09:37:12]: [iTMSTransporter] [2020-12-04 09:37:12 PST] <main> ERROR: ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'org.name.tapewarm'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."
[logs] [09:37:12]: [iTMSTransporter] [2020-12-04 09:37:12 PST] <main> ERROR: ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[logs] 
[logs] [09:37:12]: [iTMSTransporter] [2020-12-04 09:37:12 PST] <main> DBG-X: The error code is: 1102
[logs] 
[logs] [09:37:12]: [iTMSTransporter] [2020-12-04 09:37:12 PST] <main>  INFO: Done performing authentication.
[logs] 
[logs] [09:37:12]: [iTMSTransporter]
[logs] [09:37:12]: [iTMSTransporter] 
[logs] 
[logs] [09:37:12]: [iTMSTransporter] 
[logs] 
[logs] [09:37:12]: [iTMSTransporter] Package Summary:
[logs] 
[logs] [09:37:12]: [iTMSTransporter]  
[logs] 
[logs] [09:37:12]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[logs] 
[logs] [09:37:12]: [iTMSTransporter] 	/var/folders/97/73j93h690g9gdn54bh_zskm40000gn/T/d20201204-82539-1mwei59/1543439387.itmsp - Error Messages:
[logs] 
[logs] [09:37:12]: [iTMSTransporter] 		ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"
[logs] 
[logs] [09:37:12]: [iTMSTransporter] 		ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'org.name.tapewarm'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."
[logs] 
[logs] [09:37:12]: [iTMSTransporter] 		ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[logs] 
[logs] [09:37:12]: [iTMSTransporter] [2020-12-04 09:37:12 PST] <main> DBG-X: Returning 1
[logs] 
[logs] [09:37:12]: iTunes Transporter output above ^
[logs] [09:37:12]: ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface"
[logs] ERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'org.name.tapewarm'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7."
[logs] ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[logs] Return status of iTunes Transporter was 1: ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_inter\nERROR ITMS-90713: "Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'org.name.tapewarm'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for t\nERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[logs] The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[logs] [!] Error uploading ipa file, for more information see above
[logs] fastlane pilot failed
```

### PR DESCRIPTION
**Pull request by barthap**
# Why

Fixes #115 

# How

- Fixed the _"Redundant Binary Upload"_  error handling was missing in CLI

- Added error handling for (https://github.com/expo/turtle-v2/pull/341):
   - Missing App Icon (`TMS-90022`, `ITMS-90704`)
   - Invalid App Signature (`ITMS-90034`) - seems to happen when Distribution Cert, tied to app Provisioning Provile, is revoked

# Test Plan

Tested manually:
Screenshot 2020-12-10 at 13 06 51

### CODE REVIEW

File: packages/eas-cli/src/submissions/utils/errors.ts [hunk 1]
```diff
@@ -28,14 +32,30 @@ const SubmissionErrorMessages: Record<SubmissionErrorCode, string> = {
   [SubmissionErrorCode.ANDROID_MISSING_PRIVACY_POLICY]:
     'The app has permissions that require a privacy policy set for the app.\n' +
     `${learnMore('https://expo.fyi/missing-privacy-policy')}.`,
+  [SubmissionErrorCode.IOS_OLD_VERSION_CODE_ERROR]:
+    "You've already submitted this version of the app.\n" +
+    'Versions are identified by Build Numbers (expo.ios.buildNumber in app.json).\n' +
+    "If you're submitting an Expo project built with EAS Builds, increment the build number in app.json and build the project again.",
```
Comment (brentvatne) [inline packages/eas-cli/src/submissions/utils/errors.ts:38]:
```suggestion
    "If you're submitting an Expo project built with EAS Build, increment the build number in app.json and build the project again.",
```

File: packages/eas-cli/src/submissions/utils/errors.ts [hunk 2]
```diff
@@ -28,14 +32,30 @@ const SubmissionErrorMessages: Record<SubmissionErrorCode, string> = {
...
+  [SubmissionErrorCode.IOS_UNKNOWN_ERROR]:
+    "We couldn't figure out what went wrong. Please see logs to learn more.",
+  [SubmissionErrorCode.IOS_MISSING_APP_ICON]:
+    'Your iOS App Icon is missing or has invalid format. The icon must be a 1024x1024 PNG image.\n' +
```
Comment (brentvatne) [inline packages/eas-cli/src/submissions/utils/errors.ts:42]:
```suggestion
    'Your iOS app icon is missing or is an invalid format. The icon must be a 1024x1024 PNG image with no transparency.\n' +
```

File: packages/eas-cli/src/submissions/utils/errors.ts [hunk 3]
```diff
@@ -28,14 +32,30 @@ const SubmissionErrorMessages: Record<SubmissionErrorCode, string> = {
   [SubmissionErrorCode.ANDROID_MISSING_PRIVACY_POLICY]:
     'The app has permissions that require a privacy policy set for the app.\n' +
     `${learnMore('https://expo.fyi/missing-privacy-policy')}.`,
+  [SubmissionErrorCode.IOS_OLD_VERSION_CODE_ERROR]:
+    "You've already submitted this version of the app.\n" +
+    'Versions are identified by Build Numbers (expo.ios.buildNumber in app.json).\n' +
```
Comment (brentvatne) [inline packages/eas-cli/src/submissions/utils/errors.ts:37]: maybe we can link to a FYI page here instead, so it's easier to update and provide information about how to do this in managed and bare contexts

File: packages/eas-cli/src/submissions/utils/errors.ts (hunk 1 above)
Comment (brentvatne) [reply packages/eas-cli/src/submissions/utils/errors.ts:38]: same as above, would let the fyi page do the talking here.

**Comment by barthap** [comment]
Added a FYI page for bumping iOS version number message: https://github.com/expo/fyi/pull/19

File: packages/eas-cli/src/submissions/utils/errors.ts (hunk 3 above)
Comment (barthap) [reply packages/eas-cli/src/submissions/utils/errors.ts:37]: Done, however I haven't changed this message to reflect the already-existing Android counterpart:
https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/submissions/utils/errors.ts#L23-L27

Comment (brentvatne) [reply packages/eas-cli/src/submissions/utils/errors.ts:37]: ah, we should follow up and change that on the android side. i think it's because we wrote the android side prior to eas-cli existing
