### PR TITLE
fetch all certificates, and filter locally

### LINKED ISSUE #133: Invalid prov. profile for internal distribution
There's an issue with regenerating the provisioning profile when building an app for internal distribution (I haven't verified it's broken for app store builds too). The provisioning profile is generated for a different distribution certificate than the chosen one.

Repo steps:
- use the `turtle-dev` apple id and the `Alicja Warchał` team
- log in to eas-cli as `expo-turtle` (ask me for the password)
- init a new app and add this to app.json:
  ```
    "android": {
      "package": "com.expo.turtle.tutorial.internal.abc"
    },
    "ios": {
      "bundleIdentifier": "com.expo.turtle.tutorial.internal.abc"
    }
  ```
- run `eas build:configure` and complete all steps
- edit `eas-cli/packages/eas-cli/src/build/create.ts`to add `process.exit(1);` on line 20 to not spam turtle with test builds
  Screenshot 2020-12-08 at 19 01 01
- go to Apple Dev Portal and revoke the iOS dist cert with the expiry on 2021/12/08 (don't revoke the one with the expiry on 2021/11/09 - it will break turtle v1 smoke tests)
   Screenshot 2020-12-08 at 19 04 27
- create eas.json:
   ```
   {
    "builds": {
      "android": {
        "release": {
          "workflow": "generic"
        }
      },
      "ios": {
        "release": {
          "workflow": "generic",
          "distribution": "internal"
        }
      }
    } 
  }
   ```
- run `eas build -p ios` and follow all the steps, EAS CLI will regenerate the profile
- go to [Apple Dev Portal](https://developer.apple.com/account/resources/certificates/list) and see that the new profile was generated for the wrong dist cert (for the one with the expiry on 2020/11/09) - even though a new one was created
  Screenshot 2020-12-08 at 19 10 46

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- fix #133 

# How

- Download all certs and filter locally.
- Remove unused cert querying method.
- Make similar filtering change to another cert method (untested, but logical).

# Test Plan

- #133 lays out an internal test plan that I've verified.

### CODE REVIEW

File: packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts [hunk 1]
```diff
@@ -15,51 +15,30 @@ export async function getCertificateBySerialNumberAsync(
...
-  });
-  return certificate ?? null;
-}
-
 export async function getDistributionCertificateAync(
   context: RequestContext,
   serialNumber: string
 ): Promise<Certificate | null> {
-  const [certificate] = await Certificate.getAsync(context, {
+  // At most, this returns 2 values.
```
Comment (dsokal) [inline packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts:31]:
```suggestion
  // At most, this returns 3 values.
```
I think the limit is 3 🤔

**Review by dsokal — APPROVED** [review]

**Comment by dsokal** [comment]
I guess I was too slow 😅

File: packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts (hunk 1 above)
Comment (EvanBacon) [reply packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts:31]: we still query against the type (ios distribution), in which case the max is two.
Screen Shot 2020-12-08 at 12 46 33 PM
