### PR TITLE
[ENG-5536][eas-cli] add submit info to json only output

### LINKED ISSUE #1181: Build json output missing submission info
### Build/Submit details page URL

_No response_

### Summary

I'm trying to integrate our CI (GitHub Actions) with Slack. The idea is to send a message with the submission URL on every deploy. However, It seems that the json output is missing this information. Is this a bug? It seems to be a bug as the text output has this info. 

This is used to output a JSON:
https://github.com/expo/eas-cli/blob/283f086b258d507b7772129f33eae0eb355fc7c7/packages/eas-cli/src/build/runBuildAndSubmit.ts#L136

And this is only called for text output:
https://github.com/expo/eas-cli/blob/283f086b258d507b7772129f33eae0eb355fc7c7/packages/eas-cli/src/build/runBuildAndSubmit.ts#L130

### Managed or bare?

both

### Environment

Not applicable 

### Error output

_No response_

### Reproducible demo or steps to reproduce from a blank project

Run eas build with out submit and json output:

```sh
eas build --non-interactive --auto-submit --no-wait --json --platform ios --profile production
```

We got a bunch of text outputs that contains both the build URL and the submission URL:
```sh
[...]
Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
✔ Compressed project files 2s (16.5 MB)
✔ Uploaded to EAS 18s

Build details: https://expo.dev/accounts/<account id>/projects/<project id>/builds/<build id>

[...]

✔ Scheduled iOS submission

Submission details: https://expo.dev/accounts/<account id>/projects/<project id>/submissions/<submission id>
```

However, the json output is the following:
```json
[
  {
    "id": "<build id>",
    "status": "IN_QUEUE",
    "platform": "IOS",
    "artifacts": {},
    "initiatingActor": {
      "id": "<account id>",
      "displayName": "<account name>"
    },
    "project": {
      "id": "<project id>",
      "name": "<project name>",
      "slug": "<project slug>",
      "ownerAccount": {
        "id": "<account id>",
        "name": "<account name>"
      }
    },
    "releaseChannel": "default",
    "distribution": "STORE",
    "buildProfile": "production",
    "sdkVersion": "<sdk version>",
    "appVersion": "<app version>",
    "appBuildVersion": "<app build version>",
    "gitCommitHash": "<commit hash>",
    "priority": "HIGH",
    "createdAt": "2022-06-26T01:32:20.118Z",
    "updatedAt": "2022-06-26T01:32:20.118Z"
  }
]
```

Which is missing the submission info.

### PR DESCRIPTION
**Pull request by wkozyra95**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

Closes #1181 

# How

# Test Plan

Run:
- `eas build --json --no-wait --non-interactive --auto-submit`
- `eas build --json --no-wait --non-interactive`
- `eas build --json --non-interactive --auto-submit`

### CODE REVIEW

File: packages/eas-cli/src/build/runBuildAndSubmit.ts [hunk 1]
```diff
@@ -160,6 +161,7 @@ export async function runBuildAndSubmitAsync(projectDir: string, flags: BuildFla
         submitProfile,
         nonInteractive: flags.nonInteractive,
       });
+      startedBuild.build.submission = submission;
```
Comment (dsokal) [inline packages/eas-cli/src/build/runBuildAndSubmit.ts:164]: I'm not sure if I like this approach. I think it would be cleaner to refetch the build entity from GraphQL.

File: packages/eas-cli/src/build/runBuildAndSubmit.ts [hunk 2]
```diff
@@ -180,16 +182,31 @@ export async function runBuildAndSubmitAsync(projectDir: string, flags: BuildFla
...
-    await waitForSubmissionsToCompleteAsync(submissions);
+    const completedSubmissions = await waitForSubmissionsToCompleteAsync(submissions);
+    if (flags.json) {
+      printJsonOnlyOutput(
+        builds.map(build => ({
+          ...build,
+          submission: completedSubmissions.find(
+            submission => submission.platform === build?.platform
+          ),
+        }))
```
Comment (dsokal) [inline packages/eas-cli/src/build/runBuildAndSubmit.ts:206]: Same here.

**Review by dsokal — APPROVED** [review]

**Comment by wkozyra95** [comment]
/changelog-entry new-feature Add submission info when building with `--json` option.
