### PR TITLE
[eas-cli] Fix adding existing capability identifiers

### LINKED ISSUE #43677: [expo-widgets] App Group capability not synced to widget extension bundle ID during EAS Build
### Minimal reproducible example

https://github.com/weitude/expo-widgets-app-group-repro

### Steps to reproduce

1. Clone the repro repo
2. Run `eas build -p ios` (platform: iOS, EAS Build cloud, npm)
3. During credential setup, EAS CLI shows for the widget target:
   ✔ Bundle identifier registered com.example.widgetrepro.widgets
   ✔ Synced capabilities: No updates
   ✔ Synced capability identifiers: No updates
4. Build fails with:
   Provisioning profile "...[expo] com.example.widgetrepro.widgets AppStore ..."
   doesn't support the group.com.example.widgetrepro App Group.

Expected: EAS should enable the App Groups capability on the widget extension's
bundle identifier in Apple Developer Portal and assign the specified group,
so the generated provisioning profile includes it.

Actual: App Group capability is not synced for the widget extension's bundle ID.
The provisioning profile is generated without it, causing Xcode signing failure.

Workaround: Manually enable App Groups on the widget bundle ID in Apple Developer
Portal, assign the group identifier, delete the widget provisioning profile via
`eas credentials -p ios`, then rebuild.

### Environment

```text
expo-env-info 2.0.11 environment info:
    System:
      OS: macOS 26.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.14.0
      npm: 11.4.1
      Watchman: 2026.03.02.00
    Managers:
      CocoaPods: 1.16.2
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
    IDEs:
      Xcode: 26.3/17C529
    npmPackages:
      expo: ^55.0.0 => 55.0.4
      expo-router: ~55.0.4 => 55.0.4
      react: 19.2.0 => 19.2.0
      react-native: 0.83.2 => 0.83.2
    npmGlobalPackages:
      eas-cli: 18.1.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Running 17 checks on your project...
  17/17 checks passed. No issues detected!
```

### PR DESCRIPTION
**Pull request by jakex7**
# Why

When an iOS app extension target declares App Group entitlements (e.g. `'com.apple.security.application-groups': ['group.com.easwidgets']`) and the app group already exists in the Apple Developer team but is not linked to the target's bundle identifier, credential setup enabled the App Groups capability on the bundle but never attached the group resulting with capability on but 0 groups linked.
```
Current local entitlements:
{
  "com.apple.security.application-groups": [
    "group.com.easwidgets"
  ]
}
Will enable remote capability: com.apple.security.application-groups (App Groups).
Existing to disable:  [ 'FJXGJ28CQS_IN_APP_PURCHASE' ]
Patch Request: [ { capabilityType: 'APP_GROUPS', option: 'ON' } ]
✔ Synced capabilities: Enabled: App Groups
- Syncing capabilities identifiers
No capability identifiers need to be updated
✔ Synced capability identifiers: No updates
```
This is a regression introduced in https://github.com/expo/eas-cli/pull/3088/
Fixes https://github.com/expo/expo/issues/43677

# How

Fetch the bundle via `BundleId.infoAsync` to determine which IDs are already linked to this bundle.
- If it exists and ID is already linked -> skip.
- If it exists but is not linked -> just link.
- If it doesn't exist -> create it, then link (unchanged behavior).

# Test Plan

After this changes:
```
Current local entitlements:
{
  "com.apple.security.application-groups": [
    "group.com.easwidgets"
  ]
}
Will enable remote capability: com.apple.security.application-groups (App Groups).
Existing to disable:  [ '6C659CPDFA_IN_APP_PURCHASE' ]
Patch Request: [ { capabilityType: 'APP_GROUPS', option: 'ON' } ]
✔ Synced capabilities: Enabled: App Groups
- Syncing capabilities identifiers
Updating bundle identifier with capability identifiers: [
  {
    "capabilityType": "APP_GROUPS",
    "option": "ON",
    "relationships": {
      "appGroups": [
        "NW5UULASH8"
      ]
    }
  }
]
✔ Synced capability identifiers: Linked: group.com.easwidgets
```

### CODE REVIEW

File: packages/eas-cli/src/credentials/ios/appstore/capabilityIdentifiers.ts [hunk 1]
```diff
@@ -73,15 +87,31 @@ export async function syncCapabilityIdentifiersForEntitlementsAsync(
...
+
+      // Identifier already exists.
+      if (remoteIdModel) {
+        // Identifier already linked to this bundle.
+        if (alreadyLinkedOpaqueIds.has(remoteIdModel.id)) {
+          continue;
+        }
+        // Link the existing identifier to this bundle.
+        linkedIds.push(remoteIdModel.attributes.identifier);
+        capabilityIdOpaqueIds.push(remoteIdModel.id);
```
Comment (vonovak) [inline packages/eas-cli/src/credentials/ios/appstore/capabilityIdentifiers.ts:112]:
```suggestion
        if (!alreadyLinkedOpaqueIds.has(remoteIdModel.id)) {
          // Link the existing identifier to this bundle.
          linkedIds.push(remoteIdModel.attributes.identifier);
          capabilityIdOpaqueIds.push(remoteIdModel.id);
        }

```

to me, this reads a little better

**Review by vonovak — APPROVED** [review]
I left a stylistic comment, otherwise LGTM
