### PR TITLE
[eas-cli] use .pbxproj file to check if native Xcode project is present

### LINKED ISSUE #529: "eas build --platform ios" command silently fails
## What
I've managed to run `eas build --platform ios` a few times in the past, but as of today I can no longer run the command, it fails right away with the following prompt:

```
~/projects/<project-name> on master
$ eas build --platform ios
✔ Linked to project @XXX/<project-name>

We've found multiple schemes in your Xcode project:

~/projects/<project-name> on master
```

I get no prompt or anything, the process just ends.

## Why
After some debugging by manually adding logs in the CLI on my local machine (`/usr/local/lib/node_modules/eas-cli`) I've noticed that the culprit is that `scheme` is an empty array (`[]`) here: https://github.com/expo/eas-cli/blob/0e7d7f765a4a842a948a9ba13ec17a06a66ebfb0/packages/eas-cli/src/project/ios/scheme.ts#L65

## My local env
`eas-cli/0.22.0 darwin-x64 node-v12.13.0`

Please let me know if I can provide any more info to help debug the issue!

### LINKED ISSUE #530: EAS displays wrong version numbers in webhook/website for non-primary scheme builds in multi-scheme iOS projects
EAS always displays the version information from `info.plist`, regardless whether that's the right plist for the scheme that's being built.

Reproduction steps:
- Create a bare workflow project
- Create a second target/scheme
- Set unique build numbers on it
- Point to the new scheme in eas.json
- Run a build

Example of such a build: https://expo.dev/accounts/few_io/projects/Unholstered/builds/953bb450-7345-47bd-b925-5816ee5466a8.

You can compare the build versions (1.5, 57) with the values in the IPA.

Bonus points for solving the fact that the _primary_ info.plist doesn't have to be called info.plist, but the tooling assumes it does.

### PR DESCRIPTION
**Pull request by wkozyra95**
# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary.
- [ ] I've tagged the changelog entry with `[EAS BUILD API]` if it's a part of a breaking change to EAS Build API (only possible when updating `@expo/eas-build-job` package).

# Why

Closes #529

# How

- check if pbxproj exists(xcodeproj directory might exist locally for some users if project was ejected in the past, because git does not track directories)
- handle case where there is no shared scheme in the project

# Test Plan

try to start builds with
- missing pbxproj
- missing .xcscheme files

### CODE REVIEW

File: packages/eas-cli/src/project/ios/scheme.ts [hunk 1]
```diff
@@ -63,6 +63,11 @@ export async function selectSchemeAsync({
   nonInteractive?: boolean;
 }): Promise<string> {
   const schemes = IOSConfig.BuildScheme.getSchemesFromXcodeproj(projectDir);
+  if (schemes.length === 0) {
+    throw new Error(
+      'We did not found any schemes in the Xcode project, make sure that scheme is marked as "shared" in Xcode and listed in the output of "xcodebuild -list" command'
```
Comment (dsokal) [inline packages/eas-cli/src/project/ios/scheme.ts:68]:
```suggestion
      'We did not find any schemes in the Xcode project, make sure that at least one scheme is marked as "shared" in Xcode, and that it's listed in the output of "xcodebuild -list" command'
```

**Review by dsokal — APPROVED** [review]
