### PR TITLE
[ENG-7367][eas-cli] Fix using local credentials with enterprise provisioning

### LINKED ISSUE #1656: Local Credentials requiring AdHoc Provisioning Profile for Internal Distribution
When using local credentials with an enterprise universal provisioning profile the build fails, while it works when using a remote credentials source.

> ✔ Using local iOS credentials (credentials.json)
>    Error: You must use an adhoc provisioning profile (target 'TARGET')' for internal distribution

> The following will only work if you have an Apple account with Apple Developer Enterprise Program membership. While using Enterprise provisioning, you can sign your app using a **universal** or **adhoc** provisioning profile. We recommend universal because it does not require you to register your devices with Apple, which is the main benefit of using Enterprise provisioning.

This

https://github.com/expo/eas-cli/blob/2d117e5b4a56b3d6623d12c2af744a839491621a/packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts#L146

should rather check whether the provisioning profile is adhoc **or** universal.

### PR DESCRIPTION
**Pull request by wkozyra95**
# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

Closes #1656 

# How

Check if the provisioning profile is using universal provisioning for enterprise accounts when using local credentials.
Additionally, check more strictly if enterpriseProvisioning is specified in eas.json.

# Test Plan

Don't have access to the enterprise account at the moment(some policies need to be accepted), so I didn't test it, but I verfied with EAS Build sources that this is the way we validate on builider type of the Provisioning profile

### CODE REVIEW

File: packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts [hunk 1]
```diff
@@ -143,17 +143,32 @@ export default class IosCredentialsProvider {
...
+        );
+      } else if (this.options.enterpriseProvisioning === 'adhoc' && !isAdHoc) {
+        throw new Error(
+          `You must use an adhoc provisioning profile${
+            targetName ? ` (target '${targetName})'` : ''
+          } for internal distribution if you specified "enterpriseProvisioning": "adhoc" in eas.json`
+        );
+      } else if (!this.options.enterpriseProvisioning && !isEnterprise && !isAdHoc) {
+        throw new Error(
+          `You must use an adhoc provisioning profile${
```
Comment (wkozyra95) [inline packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts:162]: Most user is not aware what enterprise accounts, so decided to mention only ad hoc here, but I'm open to other suggestions.

File: packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts [hunk 2]
```diff
@@ -26,6 +26,11 @@ export function isAdHocProfile(dataBase64: string): boolean {
   return Array.isArray(provisionedDevices);
 }
 
+export function isEnterpriseUniversalProfile(dataBase64: string): boolean {
+  const profilePlist = parse(dataBase64);
+  return !!profilePlist['ProvisionsAllDevices'];
```
Comment (dsokal) [inline packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts:31]: Compare with undefined/null. Remember the enum issue from a few days ago? XD

File: packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts [hunk 3]
```diff
@@ -143,17 +143,32 @@ export default class IosCredentialsProvider {
...
-        `You must use an adhoc provisioning profile${
-          targetName ? ` (target '${targetName})'` : ''
-        } for internal distribution`
-      );
-    } else if (this.options.distribution !== 'internal' && isAdHoc) {
+    const isEnterprise = isEnterpriseUniversalProfile(provisioningProfile);
+    if (this.options.distribution === 'internal') {
+      if (this.options.enterpriseProvisioning === 'universal' && !isEnterprise) {
+        throw new Error(
+          `You must use an universal provisioning profile${
```
Comment (dsokal) [inline packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts:150]:
```suggestion
          `You must use a universal provisioning profile${
```

File: packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts [hunk 4]
```diff
@@ -143,17 +143,32 @@ export default class IosCredentialsProvider {
...
+            targetName ? ` (target '${targetName})'` : ''
+          } for internal distribution if you specified "enterpriseProvisioning": "universal" in eas.json`
+        );
+      } else if (this.options.enterpriseProvisioning === 'adhoc' && !isAdHoc) {
+        throw new Error(
+          `You must use an adhoc provisioning profile${
+            targetName ? ` (target '${targetName})'` : ''
+          } for internal distribution if you specified "enterpriseProvisioning": "adhoc" in eas.json`
+        );
+      } else if (!this.options.enterpriseProvisioning && !isEnterprise && !isAdHoc) {
```
Comment (dsokal) [inline packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts:160]:
```suggestion
      } else if (this.options.enterpriseProvisioning === undefined && !isEnterprise && !isAdHoc) {
```

**Review by dsokal — APPROVED** [review]

File: packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts (hunk 2 above)
Comment (wkozyra95) [reply packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts:31]: That issue was caused by the fact that falsy value was used as sth that represented some state. Here we are checking whether the value exists and regardless of whether it is null/undefined or any other falsy value it should work the same way. Comparing explicitly against undefined is in my opinion risky because it's easy to introduce bugs where null or undefined are mixed and not properly reflected by a type system.

File: packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts [hunk 5]
```diff
@@ -143,17 +143,32 @@ export default class IosCredentialsProvider {
...
```
Comment (waldi) [inline packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts:160]: As far as I understand not setting `enterpriseProvisioning` implicitly defaults to `adhoc`.

> [iOS](https://docs.expo.dev/build/internal-distribution/#ios)
> The configuration above tells EAS Build that you would like to use ad hoc distribution, which is available for all paid Apple Developer accounts. It is not available for free accounts.

So I think you can combine those two else if's to just:
```
     else if (!isAdHoc) {
        throw new Error(
          `You must use an adhoc provisioning profile${
            targetName ? ` (target '${targetName})'` : ''
          } for internal distribution if you specified "enterpriseProvisioning": "adhoc" in eas.json`
        );
      }
```

Comment (wkozyra95) [reply packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts:160]: There is no default, For managed credentials, If you are on regular account only AdHoc is available, so we are picking that automatically, but for Enterprise accounts you will be prompted whether you want to use AdHoc or universal provisioning. For local credentials there is no need for a prompt, because we never generate new profiles, so we don't need declaration what type it should be.

**Review by szdziedzic — APPROVED** [review]

**Comment by wkozyra95** [comment]
changelog-entry bug-fix Fix using local credentials for internal distribution builds with universal provisioning.

**Comment by wkozyra95** [comment]
/changelog-entry bug-fix Fix using local credentials for internal distribution builds with universal provisioning.
