### PR TITLE
[eas submit] Pretty-print iPad multitasking error message

### LINKED ISSUE #179: Tablet supports true build failed - iOS
eas submit -p ios failed with following output

✖ Something went wrong when submitting your app to Apple App Store.
We couldn't figure out what went wrong. Please see logs to learn more.

[logs] Starting iOS app upload
[logs] Downloading archive
[logs] Uploading iOS app to TestFlight...
[logs] [23:08:18]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[logs] [23:08:19]: -------------------
[logs] [23:08:19]: --- Step: pilot ---
[logs] [23:08:19]: -------------------
[logs] [23:08:19]: Ready to upload new build to TestFlight (App: xxx)...
[logs] [23:08:21]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[logs] [23:08:21]: Going to upload updated app to App Store Connect
[logs] [23:08:21]: This might take a few minutes. Please don't interrupt the script.
[logs] [23:09:00]: [Transporter Error Output]: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] [23:09:00]: Transporter transfer failed.
[logs] [23:09:00]:
[logs] [23:09:00]: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X:   parameter ErrorMessage = ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'.
[logs] [23:09:00]: [iTMSTransporter]  (1102)
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> ERROR: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'xxx'."
[logs] 
[logs] [23:09:00]: [iTMSTransporter]
[logs] 
[logs] [23:09:00]: [iTMSTransporter]
[logs] 
[logs] [23:09:00]: [iTMSTransporter]
[logs] 
[logs] [23:09:00]: [iTMSTransporter] Package Summary:
[logs] [23:09:00]: [iTMSTransporter]  
[logs] 
[logs] [23:09:00]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[logs] 
[logs] [23:09:00]: [iTMSTransporter]    /var/folders/97/73j93h690g9gdn54bh_zskm40000gn/T/d20201228-75969-6ph005/1498321159.itmsp - Error Messages:
[logs] 
[logs] [23:09:00]: [iTMSTransporter]            ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X: Returning 1
[logs] 
[logs] [23:09:00]: iTunes Transporter output above ^
[logs] [23:09:00]: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] Return status of iTunes Transporter was 1: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X: The error code is: 1102
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main>  INFO: Done performing authentication.
[logs] [!] Error uploading ipa file, for more information see above
[logs] fastlane pilot failed

### PR DESCRIPTION
**Pull request by barthap**
# Why

closes #179

A follow-up of https://github.com/expo/turtle-v2/pull/599 and https://github.com/expo/fyi/pull/38

# How

Pretty print that error message and displays link to a FYI page

# Test Plan

Not tested - just added error message to the list.

# Before merge

Merge https://github.com/expo/fyi/pull/38 first!

### CODE REVIEW

File: packages/eas-cli/src/submissions/utils/errors.ts [hunk 1]
```diff
@@ -57,6 +58,10 @@ const SubmissionErrorMessages: Record<SubmissionErrorCode, string> = {
     `${learnMore('https://docs.expo.io/distribution/app-signing')}`,
   [SubmissionErrorCode.IOS_INCORRECT_CREDENTIALS]:
     'Your Apple ID or app-specific password is incorrect. Please verify that you entered them correctly and try again.',
+  [SubmissionErrorCode.IOS_IPAD_INVALID_ORIENTATION]:
+    "Your app doesn't support iPad multitasking and has to require full screen.\n" +
+    "If you're submitting a managed Expo project, set the `ios.requireFullScreen` to true in app.json and build the project again.\n" +
```
Comment (brentvatne) [inline packages/eas-cli/src/submissions/utils/errors.ts:63]:
```suggestion
    "If you're submitting a managed Expo project, set the `expo.ios.requireFullScreen` to true in app.json and build the project again.\n" +
```

consistent with `expo.ios.buildNumber` and `expo.android.versionCode` above

**Review by brentvatne — APPROVED** [review]
