### PR TITLE
[eas-cli] fix detecting  `googleServicesFile` with `EAS_NO_VCS=1`

### LINKED ISSUE #577: RangeError: path should be a `path.relative()`d string, but got "./google-services.json"
This is a regression somewhere between version `0.22.4` and `0.24.1`.

My `app.json` has `expo.android.googleServicesFile` set to `"./google-services.json"`.

When running `DEBUG=* EAS_NO_VCS=1 eas build --platform all --non-interactive` I get the following error:

```text
RangeError: path should be a `path.relative()`d string, but got "./google-services.json"
    at throwError (foobar/node_modules/ignore/index.js:366:9)
    at checkPath (foobar/node_modules/ignore/index.js:385:12)
    at Ignore._test (foobar/node_modules/ignore/index.js:502:5)
    at Ignore.ignores (foobar/node_modules/ignore/index.js:541:17)
    at LocalClient.isFileIgnoredAsync (foobar/node_modules/eas-cli/build/vcs/local.js:28:29)
    at Object.checkGoogleServicesFileAsync (foobar/node_modules/eas-cli/build/build/validate.js:30:31)
    at async Object.prepareAndroidBuildAsync (foobar/node_modules/eas-cli/build/build/android/build.js:38:5)
    at async Build.startBuildAsync (foobar/node_modules/eas-cli/build/commands/build/index.js:139:37)
    at async Build.run (foobar/node_modules/eas-cli/build/commands/build/index.js:62:32)
    at async Build._run (foobar/node_modules/@oclif/command/lib/command.js:43:20)
```

Removing the leading `./` makes the problem go away. I then got the same problem with `expo.ios.googleServicesFile`. Same fix applied there fixed it.

-----

Not sure if anything needs to be done since I've found a workaround, but thought it would at least be good to bring it up for others hitting the same error, and so that a decision on what to do can be made...

### PR DESCRIPTION
**Pull request by wkozyra95**
# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary.
- [ ] I've tagged the changelog entry with `[EAS BUILD API]` if it's a part of a breaking change to EAS Build API (only possible when updating `@expo/eas-build-job` package).

# Why

Closes #577 

# How

- check if path points inside directory first
- pass normalized path (remove leading `./` with path.relative)

# Test Plan

run builds with and without EAS_NO_VCS and with services  file gitignored and outside of the repo

### CODE REVIEW

File: packages/eas-cli/src/vcs/vcs.ts [hunk 1]
```diff
@@ -62,6 +62,9 @@ export abstract class Client {
   // (optional) checks if the file is ignored, an implementation should ensure
   // that if file exists and `isFileIgnoredAsync` returns true, then that file
   // should not be included in the project tarball.
+  //
+  // @param filePath has to be a relative normalized path pointing to a file
+  // located under root of the repository
```
Comment (dsokal) [inline packages/eas-cli/src/vcs/vcs.ts:67]:
```suggestion
  // located under the root of the repository
```
